name: Build Linux packages

on:
  workflow_dispatch:
  push:
    branches: [ "main" ]
  pull_request:
    branches: [ "main" ]

jobs:
  build:
    runs-on: ubuntu-latest
    strategy:
      matrix:
        include:
          - platform: "linux/amd64"
            name: "amd64"
          - platform: "linux/arm64"
            name: "aarch64"

    steps:
      - name: Checkout
        uses: actions/checkout@v3

      - name: Setup QEMU
        uses: docker/setup-qemu-action@v3

      - name: Setup Docker buildx
        uses: docker/setup-buildx-action@v3

      - name: Compile
        run: |
          docker buildx build \
            -f Dockerfile \
            --platform ${{ matrix.platform }} \
            -o ${{ github.workspace }}/build \
            .
#      - name: Upload artifact
#        uses: actions/upload-artifact@v3
#        with:
#          name: gcfflasher-${{ matrix.name }}
#          path: build/src/*.deb

      - name: Upload binaries to release
        uses: svenstaro/upload-release-action@v2
        if: startsWith(github.ref, 'refs/tags/')
        with:
          repo_token: ${{ secrets.GITHUB_TOKEN }}
          file: build/src/*.deb
          tag: ${{ github.ref }}
          overwrite: true
          file_glob: true